"use client";
import type { Metadata } from "next";

import "./globals.css";
import { SocketProvider } from "./components/SocketContext";
import { usePathname } from "next/navigation";
import Navbar from "./components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { RecoilRoot } from "recoil";
import UsersList from "./components/UsersList";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const excludedRoutes = ["/signin", "/signup"];

  const isExcluded = excludedRoutes.includes(pathname);
  return (
    <html lang="en">
      <body className="w-full h-screen">
        <Toaster />
        {isExcluded ? (
          <>{children}</>
        ) : (
          <RecoilRoot>
            <SocketProvider>
              <Navbar />
              <div className="flex ">
                <div className="w-[300px] h-screen ">
                  <UsersList />
                </div>
                {children}
              </div>
            </SocketProvider>
          </RecoilRoot>
        )}
      </body>
    </html>
  );
}
